Added Go 'dcos package search'.
dcos/dcos-core-cli pull request #316
Opened 2019-08-12 09:40 UTC by ArmandGrillet

2019-08-12 09:41 UTC, ArmandGrillet commented
@mesosphere-ci run all integration tests

2019-08-12 12:56 UTC, ArmandGrillet commented
@mesosphere-ci run all integration tests

2019-08-12 17:11 UTC, ArmandGrillet commented
@mesosphere-ci run linux integration tests

2019-08-12 20:36 UTC, ArmandGrillet commented
@mesosphere-ci run linux integration tests

2019-08-13 06:41 UTC, ArmandGrillet commented
@mesosphere-ci run linux integration tests

2019-08-13 09:02 UTC, rgo3 requested changes

2019-08-13 09:02 UTC, rgo3 commented on .vscode/settings.json
> +{
This file probably wasn't planned to go into the commit.

2019-08-13 09:02 UTC, rgo3 commented on python/lib/dcoscli/tests/integrations/test_package.py
> +    assert b'o packages found' in stderr
```suggestion
    assert b'No packages found' in stderr
```

2019-08-13 09:02 UTC, rgo3 commented on pkg/cosmos/client.go
> +func NewClient(ctx api.Context, baseClient *httpclient.Client) (*Client, error) {
I think most of this code can be found in `pluginutil`: https://github.com/dcos/dcos-core-cli/blob/1896b885581b8db2553f8e6f66a783c9600d505e/pkg/pluginutil/pluginutil.go#L53
If the function in the `pluginutil` pkg is not returning a configurable enough client, we might want to change it a little so you can use it here instead of having most of the code duplicated. E.g. the function should take a `dcos.ConfigStoreOpts` as an argument.

2019-08-13 09:08 UTC, ArmandGrillet commented on python/lib/dcoscli/tests/integrations/test_package.py
> +    assert b'o packages found' in stderr
The issue is that we go from a `No packages found` to a `Error: no packages found`

2019-08-13 09:08 UTC, rgo3 commented on pkg/cosmos/client.go
>  // NewClient creates a new diagnostics client.
```suggestion
// NewClient creates a new cosmos client.
```

2019-08-13 09:46 UTC, ArmandGrillet commented
@mesosphere-ci run linux integration tests

2019-08-13 09:48 UTC, rgo3 commented on python/lib/dcoscli/tests/integrations/test_package.py
> +    assert b'o packages found' in stderr
Ah ok, due to the missing "n" I just thought its a typo.

2019-08-13 11:44 UTC, rgo3 commented on python/lib/dcoscli/tests/integrations/test_package.py
> +    assert b'o packages found' in stderr
```suggestion
    assert b'no packages found' in stderr
```
I'd at least add the "n" to avoid confusion, otherwise LGTM.

2019-08-13 11:45 UTC, rgo3 approved these changes

2019-08-13 11:50 UTC, ArmandGrillet commented
@mesosphere-ci run all integration tests

2019-08-13 13:48 UTC, merged