Update dcos-e2e
dcos/dcos-core-cli pull request #376
Opened 2019-10-15 11:35 UTC by bamarni

Nightly integration tests are now consistently failing.

Bumping dcos-e2e might fix the issue, which seems related to the recent
removal of dcos-history.

See https://github.com/dcos/dcos-test-utils/pull/101

https://jira.mesosphere.com/browse/DCOS_OSS-5600

2019-10-15 11:44 UTC, bamarni commented
@mesosphere-ci run linux integration tests

2019-10-15 13:44 UTC, janisz commented
What's the difference with #375

2019-10-15 17:12 UTC, bamarni commented
@mesosphere-ci run linux integration tests

2019-10-16 06:53 UTC, bamarni commented
@mesosphere-ci run linux integration tests

2019-10-16 08:42 UTC, janisz requested changes

2019-10-16 08:42 UTC, janisz commented on scripts/requirements.txt
> +dcos-e2e==2019.10.11.0
I think we should get rid of this notation. It require changes in two lines while only single line should be updated

2019-10-16 08:42 UTC, janisz commented on scripts/requirements.txt
>  --find-links git+https://github.com/dcos/dcos-test-utils.git@e8519d9c20c4f0859d90a0a1d7eeae5c3c52fe5d#egg=dcos-test-utils-0.1
dcos-e2e uses different version of dcos-test-utils. Can you update it as well?

2019-10-17 10:06 UTC, closed without merging