Remove DC/OS E2E
dcos/dcos-core-cli pull request #379
Opened 2019-10-16 10:20 UTC by bamarni

Currently we have a mix of DC/OS E2E and DC/OS Launch. We pinned an old
version of DC/OS E2E which doesn't work with DC/OS dev anymore, updating
DC/OS E2E to its latest version would probably fix the issue, this was
tried in #376 without success.

As a simple fix we can remove DC/OS E2E and stick to DC/OS Launch for
now, in the long-term we should move to the universal DC/OS installer.

2019-10-16 10:26 UTC, bamarni commented
@mesosphere-ci run all integration tests

2019-10-16 10:33 UTC, bamarni commented
@mesosphere-ci run linux integration tests

2019-10-16 10:40 UTC, bamarni commented
@mesosphere-ci run linux integration tests

2019-10-16 10:49 UTC, bamarni commented
@mesosphere-ci run linux integration tests

2019-10-16 10:50 UTC, bamarni commented
@mesosphere-ci run mac integration tests

2019-10-16 11:58 UTC, bamarni commented
@mesosphere-ci run linux integration tests

2019-10-16 11:58 UTC, bamarni commented
@mesosphere-ci run mac integration tests

2019-10-16 12:25 UTC, bamarni commented
@mesosphere-ci run linux integration tests

2019-10-16 12:26 UTC, bamarni commented
@mesosphere-ci run mac integration tests

2019-10-16 12:35 UTC, bamarni commented
@mesosphere-ci run linux integration tests

2019-10-16 12:35 UTC, bamarni commented
@mesosphere-ci run mac integration tests

2019-10-16 12:49 UTC, bamarni commented
@mesosphere-ci run linux integration tests

2019-10-16 12:49 UTC, bamarni commented
@mesosphere-ci run mac integration tests

2019-10-16 13:23 UTC, bamarni commented
@mesosphere-ci run linux integration tests

2019-10-16 13:23 UTC, bamarni commented
@mesosphere-ci run mac integration tests

2019-10-16 15:25 UTC, bamarni commented
@mesosphere-ci run linux integration tests

2019-10-16 15:25 UTC, bamarni commented
@mesosphere-ci run mac integration tests

2019-10-17 06:44 UTC, drewvanstone commented
Looks like the build is failing

2019-10-17 08:05 UTC, bamarni commented
It passed on linux but there is an escape issue on mac with the jenkinsfile, looking at it.

2019-10-17 08:32 UTC, bamarni commented
@mesosphere-ci run linux integration tests

2019-10-17 09:00 UTC, bamarni commented
@mesosphere-ci run mac integration tests

2019-10-17 09:26 UTC, bamarni commented
@mesosphere-ci run windows integration tests

2019-10-17 10:07 UTC, janisz commented
I'm not a fan of this change. Instead I'd like to invest more time and fix what was broken.

2019-10-17 11:02 UTC, bamarni commented
@mesosphere-ci run windows integration tests

2019-10-17 11:16 UTC, janisz requested changes
I need to block this PR. IMO dcos-launch is a problem not a solution. We should stay away from deprecated software.

2019-10-17 15:04 UTC, bamarni commented
@mesosphere-ci run windows integration tests

2019-10-17 15:45 UTC, janisz commented on scripts/requirements.txt
> +passlib==1.7.1
Why new dependency?

2019-10-17 15:55 UTC, bamarni commented on scripts/requirements.txt
> +passlib==1.7.1
We're relying on this dependency in the `launch_aws_cluster.py` script but it was missing here, it was still getting installed as it's an indirect dependency (through dcos-e2e).

2019-10-17 16:28 UTC, janisz approved these changes

2019-10-17 16:39 UTC, bamarni commented
@mesosphere-ci run linux integration tests

2019-10-17 16:39 UTC, bamarni commented
@mesosphere-ci run mac integration tests

2019-10-17 17:01 UTC, makkes approved these changes

2019-10-18 00:47 UTC, drewvanstone approved these changes

2019-10-18 07:05 UTC, makkes commented
@mesosphere-ci run mac integration tests

2019-10-18 07:05 UTC, makkes commented
@mesosphere-ci run windows integration tests

2019-10-18 07:06 UTC, makkes commented
I had to merge `2.1-patch.x` in in order to be able to merge this.

2019-10-18 09:24 UTC, bamarni commented
I'll rebase to keep the history clean and remove the extra lines in Go

2019-10-18 09:26 UTC, bamarni commented
@mesosphere-ci run all integration tests

2019-10-18 10:41 UTC, bamarni commented
I've canceled the windows build as the previous one already passed, it seemed stuck trying to spin-up the cluster (we can track if it happens again in https://jira.mesosphere.com/browse/DCOS_OSS-5614).

2019-10-18 10:41 UTC, merged