Update helloworld universe
dcos/dcos-core-cli pull request #382
Opened 2019-10-21 12:39 UTC by janisz

Fixes: https://jira.mesosphere.com/browse/DCOS-58530

2019-10-21 12:39 UTC, janisz commented
@mesosphere-ci run linux integration tests

2019-10-21 14:02 UTC, janisz commented
@mesosphere-ci run linux integration tests

2019-10-21 14:40 UTC, janisz commented
@mesosphere-ci run linux integration tests

2019-10-21 16:06 UTC, janisz commented
@mesosphere-ci run linux integration tests

2019-10-22 04:56 UTC, drewvanstone approved these changes

2019-10-22 06:50 UTC, makkes requested changes
Integration tests are failing b/c the URL is different.

2019-10-22 09:50 UTC, janisz commented
@mesosphere-ci run linux integration tests

2019-10-22 11:02 UTC, janisz commented
@mesosphere-ci run linux integration tests

2019-10-22 11:04 UTC, janisz commented on python/lib/dcoscli/tests/integrations/test_sanity.py
> -def test_package_describe():
Removed this test because it duplicates https://github.com/dcos/dcos-core-cli/pull/382/files#diff-f8ddb21a8ba9f7855ba87efde3fbd102R194

2019-10-22 11:53 UTC, janisz commented
@mesosphere-ci run linux integration tests

2019-10-22 13:46 UTC, bamarni commented
@mesosphere-ci run mac integration tests

2019-10-22 13:46 UTC, bamarni commented
@mesosphere-ci run windows integration tests

2019-10-22 13:49 UTC, makkes approved these changes

2019-10-22 16:02 UTC, bamarni approved these changes

2019-10-22 16:02 UTC, merged