Make local installed apps ovverride Cosmos Apps
dcos/dcos-core-cli pull request #405
Opened 2019-11-19 12:13 UTC by janisz

`dcos package --json` and `dcos package --cli --json` may results in different responses. To keep backward compatibility we need to make locally installed packages overrides cosmos response.

This happens only for packages that has cli and app.

**Backports:** https://github.com/dcos/dcos-core-cli/pull/396
**Reverts:** https://github.com/dcos/dcos-core-cli/pull/389/commits/5cb304b532da5b22b40d21bcb9716c60bf24f9e1
**Fixes:** https://jira.mesosphere.com/browse/DCOS_OSS-5657

2019-11-19 12:40 UTC, armandgrillet approved these changes

2019-11-19 21:50 UTC, janisz commented
Rebase on https://github.com/dcos/dcos-core-cli/pull/406 to fix CI E2E failures

2019-11-20 07:48 UTC, makkes requested changes
CI failing, otherwise lgtm

2019-11-20 13:33 UTC, makkes approved these changes

2019-11-20 14:03 UTC, merged