Change marathon app stop into Go
dcos/dcos-core-cli pull request #411
Opened 2019-11-22 14:33 UTC by br-lewis

Addresses: https://jira.mesosphere.com/browse/DCOS-60277

2019-11-25 15:55 UTC, br-lewis commented
@mesosphere-ci run mac integration tests

2019-11-25 15:56 UTC, br-lewis commented
Looks like mac test failed due to transient issue not related to this PR

`STDERR: URL [https://34.205.33.156/service/marathon/v2/deployments] is unreachable.`

2019-11-25 17:47 UTC, janisz commented on pkg/cmd/marathon/app/app_stop_test.go
> +	ctx.SetCluster(cluster)
extract to function

2019-11-25 17:47 UTC, janisz commented on pkg/cmd/marathon/app/app_stop_test.go
> +	}{
Create a type and use in all tests
```
type app struct {
	App goMarathon.Application `json:"app"`
}
```

2019-11-25 18:00 UTC, janisz commented on pkg/cmd/marathon/app/app_stop_test.go
> +}
How about this. It's easier to read and easy to turn into table test

```go
package app

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/dcos/dcos-cli/pkg/config"
	"github.com/dcos/dcos-cli/pkg/mock"
	goMarathon "github.com/gambol99/go-marathon"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

type app struct {
	App goMarathon.Application `json:"app"`
}

const testID = "test"

func TestAppStop(t *testing.T) {
	app := app{
		App: goMarathon.Application{
			ID:        testID,
			Instances: intPointer(3),
		},
	}
	deployment := goMarathon.DeploymentID{
		DeploymentID: "5ed4c0c5-9ff8-4a6f-a0cd-f57f59a34b43",
		Version:      "2015-09-29T15:59:51.164Z",
	}

	ts := router(
		func(w http.ResponseWriter, r *http.Request) { encode(w, app) },
		func(w http.ResponseWriter, r *http.Request) { encode(w, deployment) },
	)

	ctx, out := newContext(ts)

	err := appStop(ctx, "/test", false)
	require.NoError(t, err)

	assert.Equal(t, "Created deployment 5ed4c0c5-9ff8-4a6f-a0cd-f57f59a34b43\n", out.String())

}

func TestAppStopWhenAppIsStopped(t *testing.T) {
	app := app{
		App: goMarathon.Application{
			ID:        testID,
			Instances: intPointer(0),
		},
	}

	ts := router(
		func(w http.ResponseWriter, r *http.Request) { encode(w, app) },
		nil,
	)

	ctx, _ := newContext(ts)

	err := appStop(ctx, "/test", false)
	assert.EqualError(t, err, "app '/test' already stopped: 0 instances")
}

func TestAppStopWhenAppDoesntExist(t *testing.T) {
	ts := router(
		func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(http.StatusNotFound)
		},
		func(w http.ResponseWriter, r *http.Request) {
			require.Fail(t, "unexpected call to endpoint")
		},
	)

	ctx, _ := newContext(ts)

	err := appStop(ctx, "/test", false)
	assert.EqualError(t, err, "app '/test' does not exist")
}

func TestAppStopForce(t *testing.T) {
	app := app{
		App: goMarathon.Application{
			ID:        testID,
			Instances: intPointer(2),
		},
	}
	deployment := goMarathon.DeploymentID{
		DeploymentID: "5ed4c0c5-9ff8-4a6f-a0cd-f57f59a34b43",
		Version:      "2015-09-29T15:59:51.164Z",
	}

	ts := router(
		func(w http.ResponseWriter, r *http.Request) { encode(w, app) },
		func(w http.ResponseWriter, r *http.Request) {
			assert.Contains(t, r.URL.Query(), "force")
			encode(w, deployment)
		},
	)

	ctx, _ := newContext(ts)

	err := appStop(ctx, "/test", true)
	assert.NoError(t, err)
}

func TestAppStopWhenDeploymentBlocked(t *testing.T) {
	app := app{
		App: goMarathon.Application{
			ID:        testID,
			Instances: intPointer(2),
		},
	}

	ts := router(
		func(w http.ResponseWriter, r *http.Request) { encode(w, app) },
		func(w http.ResponseWriter, r *http.Request) { w.WriteHeader(409) },
	)

	ctx, _ := newContext(ts)

	err := appStop(ctx, "/test", false)
	assert.EqualError(t, err, "changes blocked: deployment already in progress for app")
}

func encode(w http.ResponseWriter, obj interface{}) {
	json.NewEncoder(w).Encode(obj)
}

func router(getFunc http.HandlerFunc, putFunc http.HandlerFunc) *httptest.Server {
	return httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch url := r.URL.Path; url {
		case "/service/marathon/v2/apps/test":
			switch r.Method {
			case http.MethodGet:
				getFunc(w, r)
			case http.MethodPut:
				putFunc(w, r)
			default:
				panic("unexpected http verb " + r.Method)
			}
		default:
			panic("unexpected call to endpoint " + url)
		}
	}))
}

func newContext(ts *httptest.Server) (*mock.Context, *bytes.Buffer) {
	out := new(bytes.Buffer)
	env := mock.NewEnvironment()
	env.Out = out
	ctx := mock.NewContext(env)
	cluster := config.NewCluster(nil)
	cluster.SetURL(ts.URL)
	ctx.SetCluster(cluster)
	return ctx, out
}

```

2019-11-25 18:24 UTC, janisz commented on pkg/cmd/marathon/app/app_stop_test.go
> +}
Expecially for @drewvanstone 

```go
package app

import (
	"bytes"
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/dcos/dcos-cli/pkg/config"
	"github.com/dcos/dcos-cli/pkg/mock"
	goMarathon "github.com/gambol99/go-marathon"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const testID = "test"

func TestAppStop(t *testing.T) {
	simpleApp := struct {
		App goMarathon.Application `json:"app"`
	}{App: goMarathon.Application{
		ID:        testID,
		Instances: intPointer(2),
	}}
	tests := []struct {
		name    string
		force   bool
		getFunc http.HandlerFunc
		putFunc http.HandlerFunc
		out     string
		err     error
	}{
		{
			getFunc: encodeFunc(simpleApp),
			putFunc: encodeFunc(goMarathon.DeploymentID{
				DeploymentID: "5ed4c0c5-9ff8-4a6f-a0cd-f57f59a34b43",
				Version:      "2015-09-29T15:59:51.164Z",
			}),
			out: "Created deployment 5ed4c0c5-9ff8-4a6f-a0cd-f57f59a34b43\n",
		},
		{
			name: "when app is stopped",
			getFunc: encodeFunc(struct {
				App goMarathon.Application `json:"app"`
			}{App: goMarathon.Application{
				ID:        testID,
				Instances: intPointer(0),
			}}),
			err: errors.New("app '/test' already stopped: 0 instances"),
		},
		{
			name:    "when app doesn't exist",
			getFunc: http.NotFound,
			err:     errors.New("app '/test' does not exist"),
		},
		{
			name:    "with force",
			force:   true,
			getFunc: encodeFunc(simpleApp),
			putFunc: func(w http.ResponseWriter, r *http.Request) {
				assert.Contains(t, r.URL.Query(), "force")
				encode(w, goMarathon.DeploymentID{
					DeploymentID: "5ed4c0c5-9ff8-4a6f-a0cd-f57f59a34b43",
					Version:      "2015-09-29T15:59:51.164Z",
				})
			},
			out: "Created deployment 5ed4c0c5-9ff8-4a6f-a0cd-f57f59a34b43\n",
		},
		{
			name:    "when deployment is blocked",
			getFunc: encodeFunc(simpleApp),
			putFunc: func(w http.ResponseWriter, r *http.Request) { w.WriteHeader(409) },
			err:     errors.New("changes blocked: deployment already in progress for app"),
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ts := router(tt.getFunc, tt.putFunc)
			ctx, out := newContext(ts)

			err := appStop(ctx, "/test", tt.force)

			require.Equal(t, tt.err, err)
			assert.Equal(t, tt.out, out.String())
		})
	}
}

func encodeFunc(obj interface{}) func(w http.ResponseWriter, r *http.Request) {
	return func(w http.ResponseWriter, r *http.Request) { encode(w, obj) }
}

func encode(w http.ResponseWriter, obj interface{}) {
	json.NewEncoder(w).Encode(obj)
}

func router(getFunc http.HandlerFunc, putFunc http.HandlerFunc) *httptest.Server {
	return httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch url := r.URL.Path; url {
		case "/service/marathon/v2/apps/test":
			switch r.Method {
			case http.MethodGet:
				getFunc(w, r)
			case http.MethodPut:
				putFunc(w, r)
			default:
				panic("unexpected http verb " + r.Method)
			}
		default:
			panic("unexpected call to endpoint " + url)
		}
	}))
}

func newContext(ts *httptest.Server) (*mock.Context, *bytes.Buffer) {
	out := new(bytes.Buffer)
	env := mock.NewEnvironment()
	env.Out = out
	ctx := mock.NewContext(env)
	cluster := config.NewCluster(nil)
	cluster.SetURL(ts.URL)
	ctx.SetCluster(cluster)
	return ctx, out
}

```

2019-11-26 10:14 UTC, janisz approved these changes
LGTM

2019-11-26 11:32 UTC, armandgrillet approved these changes

2019-11-26 12:01 UTC, janisz requested changes
Take a look at https://github.com/dcos/dcos-core-cli/pull/417#discussion_r350699733

2019-11-26 12:01 UTC, janisz commented on pkg/cmd/marathon/app/app_stop_test.go
> +	ctx.SetCluster(cluster)
https://github.com/dcos/dcos-core-cli/pull/417#discussion_r350699733

2019-11-26 14:51 UTC, merged