WIP: DCOS 60393
dcos/dcos-core-cli pull request #421
Opened 2019-11-28 15:08 UTC by ArmandGrillet

2019-12-02 10:17 UTC, janisz requested changes

2019-12-02 10:17 UTC, janisz commented on pkg/cmd/marathon/debug/debug_details.go
> +			return marathonDebugDetails(ctx, client, args[0], jsonOutput)
https://github.com/dcos/dcos-core-cli/pull/422#discussion_r352512715

2019-12-02 12:56 UTC, janisz approved these changes

2019-12-02 13:01 UTC, janisz commented on pkg/cmd/marathon/debug/debug_details.go
> +					isConstraintOK("DeclinedScarceResources", reasons),
How about extracting this values to constants and keep them in marathon client?
```go
const UnfulfilledRole = "UnfulfilledRole"
const UnfulfilledConstraint = "UnfulfilledConstraint"
const InsufficientCpus = "InsufficientCpus"
const InsufficientMemory = "InsufficientMemory"
const InsufficientDisk = "InsufficientDisk"
const InsufficientPorts = "InsufficientPorts"
const DeclinedScarceResources = "DeclinedScarceResources"
```
https://github.com/dcos/dcos-core-cli/pull/422#discussion_r352581156

2019-12-03 11:31 UTC, merged

2019-12-03 12:32 UTC, br-lewis approved these changes