Port 'dcos marathon debug summary' in Go.
dcos/dcos-core-cli pull request #422
Opened 2019-12-02 09:56 UTC by ArmandGrillet

Resolves https://jira.mesosphere.com/browse/DCOS-60395

2019-12-02 10:10 UTC, janisz commented on pkg/cmd/marathon/debug/debug_summary.go
> +			return marathonDebugSummary(ctx, client, args[0], jsonOutput)
I think we miss `Args:  cobra.ExactArgs(1),` since `args[0]` might cause panic.

2019-12-02 10:11 UTC, janisz requested changes

2019-12-02 10:11 UTC, janisz commented on pkg/cmd/marathon/debug/debug_summary.go
> +			return marathonDebugSummary(ctx, client, args[0], jsonOutput)
I think we miss `Args:  cobra.ExactArgs(1),`. `args[0]` can panic.

2019-12-02 10:13 UTC, janisz requested changes
Linter is failing

2019-12-02 13:01 UTC, janisz requested changes

2019-12-02 13:01 UTC, janisz commented on pkg/cmd/marathon/debug/debug_summary.go
> +					fmt.Sprintf("%d/%d", reasons["UnfulfilledRole"], agents),
How about extracting this to const in marathon client. The same string is used below and in another command https://github.com/dcos/dcos-core-cli/pull/421/files#diff-4522a69b4736665414222f529db51411R65-R71

2019-12-03 12:51 UTC, br-lewis approved these changes

2019-12-03 13:29 UTC, merged